### PR TITLE
Fix IBC tools for nontrivial qshift

### LINKED ISSUE #26: IBC tools do not work for nontrivial qshift
I don't know whether this is due to changes elsewhere in the toolkit (e.g. the triangular MPO solvers), or because I never tested this properly.

TODO:
- Make sure every IBC tool works properly if the boundaries have nontrivial quantum number shifts.
- Boundary streaming will not work if we need to expand the size of the window, since we need to apply a qshift to the boundary. We probably need to a `LeftQShift` and `RightQShift` to the IBCWavefunction class (and maybe also EAWavefunction), so the left and right boundaries stay the same, but these objects will keep track of the quantum number shift of the window.
- `mp-excitation-ansatz` should be enhanced to allow the qshift of the window to be specified (currenly, it uses the same qshift as the ground state). This can probably be done by applying the shift to one of the boundaries.

### PR DESCRIPTION
**Pull request by jesse-osborne**
Work in progress: #26.

### CODE REVIEW

File: wavefunction/ibc.cpp [hunk 1]
```diff
@@ -383,6 +383,8 @@ class ConstIBCIterator
 
          if (Index < WindowLeftIndex)
          {
+            inplace_qshift(PsiLeft, PsiLeft.qshift());
```
Comment (ianmccul) [inline wavefunction/ibc.cpp]: The PsiLieft should be read-only.  Is this where you want a qshift at the end of the window instead?

Comment (jesse-osborne) [reply wavefunction/ibc.cpp]: PsiLeft here is a copy of the original PsiLeft stored inside of the IBCWavefunction. This is part of the code for calculating expectation values. Ideally, it should be possible for this to be done without having to apply qshifts to the boundaries, but I couldn't think of a better way at the time to get something that works for mixed expectation values.

The code for calculating expectation values and overlaps that I put into wavefunction/ibc.cpp could probably be done in a better way, but it is (mostly) functional, so I haven't tried to improve it yet.

This change is actually a hack: `mp-ibc-join` currently doesn't apply a qshift to the left boundary when saving the wavefunction, so the Basis2 of PsiLeft doens't match with the Basis1 of Window.LeftU. Once I add `LeftQShift` and `RightQShift` to IBCWavefunction, this will change to something like `inplace_qshift(PsiLeft, Psi.left_qshift());`

**Comment by jesse-osborne** [comment]
You can now specify the quantum number of the B-matrix in the excitation ansatz (this just does a qshift on the left boundary).

The only difficulty is if you want an excitation with fractionalised quantum numbers: for the $U(1)\times U(1)$ Hubbard model, the solution that I found was to create two wavefunctions for the ground state, one where the zero particle sector at the boundary has integer spin quantum numbers, and one where it has half-integer spin quantum numbers. You can then use both of ground states together to find an excitation with a fractionalised quantum number such as `1,0` or `0,0.5`.

**Comment by ianmccul** [comment]
ok, we can easily add a tool to do a qshift of an MPS - it would be useful for schwinger model too, since that corresponds to shifting the background electric field.
Not sure why you needed to construct two wavefunctions, can't you put the fractional shift into some qshift somewhere?

**Comment by jesse-osborne** [comment]
Actually, I don't think I did it right for fractionalised quantum numbers.

At the moment, the X-matrices (from the parametrisation $B^s = N_L^s X$, where $N_L^s$ is the null space) transform as the identity quantum number. This seems to work if the quantum number of the excitation is a product of quantum numbers in the local basis, otherwise (such as with `0,0.5` and `1,0`) the X-matrix has dimension zero, and the program fails.

(For the $U(1)$ spin-1 Heisenberg model, I can get the gaps to the two- and three-magnon bands correctly by looking at excitations with different quantum numbers.)

If I set the X-matrices to have a different quantum number, then if I try to calculate `B = prod(NL, X)`, it fails because of the precondition `is_scalar(Op.TransformsAs())` in `prod`. I guess this is not allowed since it would change the local basis?

**Comment by jesse-osborne** [comment]
Rereading the last couple of paragraphs in Section II in https://doi.org/10.1103/PhysRevB.97.235155, it looks like they apply the quantum number shift to the local degrees of freedom instead of the virtual degrees of freedom at the unit cell boundary. This way, you automatically end up fractional quantum numbers in your local basis.

@ianmccul How feasible do you think this is to implement?

**Comment by ianmccul** [comment]
Right, there is something I'm missing here, because there aren't any available local basis states in the Hubbard model that will take you from an 'even parity' (N+2s)%2 = 0 to an 'odd parity' (N+2s)%2 = 1 state.  I can't remember how Valentin resolved this.  But is the solution simply that the X has to have a non-zero quantum number?  In that case, yeah prod(NL,X) won't work because it would change the local Hilbert space of NL, but there are workarounds.
I just saw your last message, yes we could qshift the local basis states, maybe that is the best way.  Another option is to keep the $X$ matrix around, which would supply the needed qshift.  And we need a function to calculate $A^s X \rightarrow X' A'^s$ without using prod().

**Comment by jesse-osborne** [comment]
It turns out that shifting the local basis isn't needed: it is mathematically equivalent to shifting the virtual basis at the unit cell boundary at the end, and it just makes this method more intuitive.

(Also, doing the qshift on the local bases would get rid of the bookkeeping of qshifts each time you go through the unit cell, and could probably simplify a lot of this code. But I guess the devil you know is better than the one you don't.)

If you have a wavefunction in the $U(1)\times U(1)$ Hubbard model with an 8-site unit cell with qshift $(6,2)$, then the wavefunction rotated by 1 site will be the same, but shifted by the fractional quanum number $(3/4,1/4)$, and if you rotate by 4 sites, it will shifted by $(3,1)$. You can then shift by the integer quantum numbers $(-2,-1)$ and $(-3,-0.5)$ to find the chargon and spinon excitations with $(1,0)$ and $(0,0.5)$.

I was able to get the dispersion relations for the XXZ model in Figs 3 and 4 in that paper by rotating the MPS unit cell (I only actually calculated the peaks and troughs, and got pretty much the same values: I would imagine that the full dispersion relations would be the same).

**Comment by jesse-osborne** [comment]
For EA wavefunctions, I think it's a good idea to track the rotation of the boundaries in the EA file, rather than creating a new file for the boundary with a rotated unit cell. This would make it easier to splice two wavepackets, since the boundary unit cells will always have the same rotation.

What I am unsure about at the moment is whether it makes sense to track the rotation of only one of the boundaries or of both of them.

At the moment, the EA wavefunction files consist of a left boundary, a right boundary, and a vector of windows (which are `WavefunctionSectionLeft`s). The unit cell sizes of the left and right boundaries are the same as the size of the vector of windows (so each window starts at a different position in the unit cell).

It currently assumes that the unit cells of the left and right boundaries and the window vector all start at the same position: then we can rotate the right window by storing the starting index for the right unit cell. We can then assume that the left unit cell and the window vector start at the same index: if we want to rotate the left unit cell, we can just rotate the elements of the window vector instead. Alternatively, we can also save the index that the left unit cell starts, which might be nicer, since we wouldn't have to move the front element of the window vector to the back or vice versa.

(The use case for needing to rotate both the left and right boundaries independently is if we want to expand the windows, which may show up in the two-particle excitation ansatz or momentum-resolved time evolution, or maybe even for the single-particle excitation ansatz if we want to increase the window size.)

At the moment, I think it's better to add both a `LeftIndex` and a `RightIndex`, even if it is a bit redundant.

**Comment by ianmccul** [comment]
I agree keeping track of a rotation of the unit cell for both the left and right is fine, even if it isn't used.
Expanding the window doesn't need to require rotating the unit cells though, but maybe that is the easiest way. Indeed, that would avoid having to keep track separately the number of sites that the window has incorporated of the unit cell.

**Comment by jesse-osborne** [comment]
>Expanding the window doesn't need to require rotating the unit cells though

I meant that for EA wavefunctions, there is a window for each position in the unit cell, so if you add one site to the left of each window, each window will start at the previous site in the unit cell, which means that you either have to move the first window in the vector to the back, or you can rotate the unit cell of the left boundary one site to the left.

**Comment by jesse-osborne** [comment]
Everything that I've tested works for nontrivial qshifts now.

But I think `mp-ibc-wavepacket` doesn't work at the moment for wavefunctions with a unit cell different from the lattice unit cell.

**Comment by ianmccul** [comment]
Thinking some more, you always want to keep the unit cell of the infinite strips consistent, since it need not be translationally invariant under single-site shifts (or need not have the same local hilbert space under single site shifts either)

**Comment by jesse-osborne** [comment]
Everything seems to work fine now. There are some outstanding problems that I probably won't fix right now:

- The way that `mp-ibc-wavefunction` localises wavepackets for cylinders probably won't work when the lattice unit cell size and the number of different y-momenta are different. I am not very satisfied with how the localisation works in 2D at the moment anyway, so I would like to come up with a better scheme in the future anyway.
- In `mp-info`, the behaviour of `ShowWavefunction` for `EAWavefunction` is that it shows the information for the left boundary. It would probably be nice to be able to look at each of the different windows, but I can't think of a simple way of implementing it, and since there are no tools which create an `EAWavefunction` with windows larger than one site, it doesn't really matter at the moment.

---

@ianmccul I will merge this into the ibc-tdvp branch soon, unless you have any issues?
